import {test,expect} from '@playwright/test';

test('project filters, case study tabs, and screenshot preview work',async({page},testInfo)=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/projects');
  await expect(page.locator('.case-study')).toHaveCount(6);
  const sentiment=page.locator('#sentiment');
  await expect(sentiment.getByRole('link',{name:'Live app'})).toHaveAttribute('href','https://moodify2-o.vercel.app/');
  await sentiment.getByRole('button',{name:'Enlarge Moodify screenshot'}).click();
  await expect(page.getByRole('dialog',{name:'Moodify screenshot'})).toBeVisible();
  await expect(page.getByRole('dialog').locator('img')).toHaveAttribute('src','/images/moodify-screen.png');
  await page.getByRole('button',{name:'Close screenshot'}).click();
  const clinical=page.locator('#clinsight');
  await expect(page.locator('.case-result')).toHaveCount(0);
  await expect(clinical.locator('.case-overview-sections section')).toHaveCount(3);
  await expect(clinical.getByRole('tabpanel')).toContainText('SentenceTransformers');
  await expect(clinical.getByRole('tabpanel')).toContainText('reduced review time by 70%');
  await clinical.getByRole('tab',{name:'How I built it'}).click();
  await expect(clinical.getByRole('tabpanel')).toContainText('60% efficiency gain');
  await clinical.getByRole('tab',{name:'How I built it'}).focus();
  await page.keyboard.press('ArrowRight');
  await expect(clinical.getByRole('tab',{name:'Tech stack'})).toBeFocused();
  await expect(clinical.getByRole('tabpanel')).toContainText('SentenceTransformers');
  await clinical.getByRole('tab',{name:'Overview'}).click();
  await clinical.getByRole('button',{name:'Enlarge ClinSight AI screenshot'}).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(clinical.getByRole('button',{name:'Enlarge ClinSight AI screenshot'})).toBeFocused();
  await clinical.getByRole('button',{name:'Close case study'}).click();
  await expect(clinical.getByRole('tablist')).toHaveCount(0);
  await clinical.getByRole('button',{name:'Explore case study'}).click();
  await page.getByRole('button',{name:'Developer tools',exact:true}).click();
  await expect(page.locator('.case-study')).toHaveCount(1);
  await expect(page.locator('#gitbot')).toBeVisible();
  await expect(page.locator('#gitbot').getByRole('link',{name:'Live app'})).toHaveAttribute('href','https://gitbot-chatbot.vercel.app/');
  await page.getByRole('button',{name:'Enlarge GitBOT screenshot'}).click();
  await expect(page.getByRole('dialog',{name:'GitBOT screenshot'}).locator('img')).toHaveAttribute('src','/images/gitbot-screen.png');
  await page.getByRole('button',{name:'Close screenshot'}).click();
  await page.getByRole('button',{name:'Explore case study'}).click();
  await page.getByRole('tab',{name:'Tech stack'}).click();
  await expect(page.getByRole('tabpanel')).toContainText('Python');
  await page.getByRole('button',{name:'Previews',exact:true}).click();
  await expect(page.locator('.case-study')).toHaveCount(2);
  await expect(page.locator('#pantry').getByRole('link',{name:'Live app'})).toHaveAttribute('href','https://shopvoice-delta.vercel.app/');
  await expect(page.locator('#store').getByRole('link',{name:'Code'})).toHaveAttribute('href','https://github.com/Void-Anvesha/Store-Intelligence');
  await expect(page.locator('#store')).not.toContainText('walkthrough');
  await expect(page.locator('#pantry').getByRole('button',{name:'Explore case study'})).toBeVisible();
  await expect(page.locator('#store').getByRole('button',{name:'Explore case study'})).toHaveCount(0);
  await page.getByRole('button',{name:'Enlarge Pantry AI screenshot'}).click();
  await expect(page.getByRole('dialog',{name:'Pantry AI screenshot'}).locator('img')).toHaveAttribute('src','/images/pantry-screen.png');
  await page.getByRole('button',{name:'Close screenshot'}).click();
  await page.locator('#pantry').getByRole('button',{name:'Explore case study'}).click();
  await expect(page.locator('#pantry').getByRole('tabpanel')).toContainText('browser speech recognition');
  await page.getByRole('button',{name:'All projects',exact:true}).click();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:`test-results/${testInfo.project.name}-interactive-projects.png`});
  await page.getByRole('button',{name:'Switch to light theme'}).click();
  await clinical.getByRole('tab',{name:'Tech stack'}).click();
  await expect(clinical.getByRole('tabpanel')).toBeVisible();
  expect(errors).toEqual([]);
});
