// Reproducible design preview based on the user's Store Intelligence reference.
// This renders a static dashboard concept, not a live application.
import {chromium} from '@playwright/test';
const metrics=[['Footfall','4','Unique visitors today'],['In store now','3','Current occupancy'],['Conversion rate','100%','Visitors → purchase'],['Total GMV','₹44,920','Revenue today'],['Average basket','₹1,871.67','Per transaction'],['Queue depth','0','Billing counter']];
const stages=[['Entered store',4,100],['Browsed zone',1,25],['Reached billing',1,25],['Completed purchase',1,25]];
const html=`<!doctype html><html lang="en"><meta charset="UTF-8"><title>Store Intelligence · Dashboard design preview</title><style>
*{box-sizing:border-box}body{margin:0;background:#0b1420;color:#eef3f8;font-family:Arial,sans-serif}header{height:94px;border-bottom:1px solid #263344;display:flex;align-items:center;justify-content:space-between;padding:0 48px;background:#101c2b}.brand{display:flex;align-items:center;gap:15px;font-size:23px;font-weight:700}.mark{width:38px;height:38px;background:#123f40;color:#62daca;border:1px solid #276260;border-radius:10px;display:grid;place-items:center;font-size:23px}.status{font-size:12px;color:#90a5b8}.status i{display:inline-block;width:7px;height:7px;background:#5ad4be;border-radius:50%;margin-right:8px}main{padding:36px 48px}h1{font-size:30px;letter-spacing:-.7px;margin:0 0 10px}p{color:#93a7ba;font-size:14px;margin:0}.heading{display:flex;align-items:center;justify-content:space-between;margin-bottom:30px}.date{padding:10px 15px;border:1px solid #304155;border-radius:7px;color:#c5d2df;font-size:13px}.metrics{display:grid;grid-template-columns:repeat(6,1fr);gap:14px;margin-bottom:30px}.metric{background:#132131;border:1px solid #29394a;border-radius:12px;padding:22px 18px}.label{font-size:12px;color:#a5b7c8;margin-bottom:19px}.value{font-size:29px;font-weight:700;letter-spacing:-1px;white-space:nowrap;margin-bottom:12px}.metric p{font-size:11px}.metric:nth-child(4){background:#123332;border-color:#2b6058}.metric:nth-child(4) .value{color:#72e0ca}.funnel{border:1px solid #29394a;border-radius:12px;background:#101e2d;padding:28px 30px}h2{font-size:19px;margin:0 0 8px}.funnel-header{display:flex;align-items:start;justify-content:space-between;margin-bottom:28px}.tag{font-size:11px;padding:8px 11px;border-radius:5px;background:#1a2b3d;color:#adc4d6}.columns,.row{display:grid;grid-template-columns:200px 1fr 65px 70px;gap:24px;align-items:center}.columns{font-size:10px;letter-spacing:1px;text-transform:uppercase;color:#8299af;padding-bottom:16px;border-bottom:1px solid #25374a}.row{min-height:66px;border-bottom:1px solid #213245;font-size:13px}.row:last-child{border:0}.track{height:9px;background:#223346;border-radius:5px;overflow:hidden}.bar{height:100%;background:#59c9ba;border-radius:5px}.row:nth-child(odd) .bar{background:#60adc8}.num{text-align:right;font-weight:700}.share{text-align:right;color:#a5b9cc}.stage{display:flex;gap:12px;align-items:center}.step{font-size:10px;color:#7d9caf}footer{display:flex;justify-content:space-between;font-size:11px;color:#71899e;margin-top:21px}
</style><header><div class="brand"><span class="mark">▥</span>Store Intelligence</div><span class="status"><i></i>Store overview</span></header><main><div class="heading"><div><h1>Retail overview</h1><p>Brigade Road, Bangalore</p></div><span class="date">Today · Last updated 12:26:54 PM</span></div><div class="metrics">${metrics.map(([label,value,description])=>`<div class="metric"><div class="label">${label}</div><div class="value">${value}</div><p>${description}</p></div>`).join('')}</div><section class="funnel"><div class="funnel-header"><div><h2>Conversion funnel</h2><p>A view of the customer journey, from entry to purchase.</p></div><span class="tag">In-store journey</span></div><div class="columns"><span>Journey stage</span><span>Share of visitors</span><span>Visitors</span><span>Share</span></div>${stages.map(([name,count,percent],i)=>`<div class="row"><span class="stage"><span class="step">0${i+1}</span>${name}</span><div class="track"><div class="bar" style="width:${percent}%"></div></div><span class="num">${count}</span><span class="share">${percent}%</span></div>`).join('')}</section><footer><span>STORE INTELLIGENCE / ANALYTICS</span><span>Dashboard design preview · Figures from supplied reference</span></footer></main></html>`;
const browser=await chromium.launch({channel:'msedge'});
try{
  const page=await browser.newPage({viewport:{width:1440,height:820},deviceScaleFactor:1});
  await page.setContent(html);
  await page.screenshot({path:'public/images/store-intelligence-preview.png',fullPage:true});
}finally{await browser.close();}
